excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Framework
disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - todo
  - file_length
  - type_body_length
opt_in_rules:
  - anyobject_protocol
  #- array_init
  #- closure_body_length
  #- closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  #- empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  #- extension_access_modifier
  - fallthrough
  #- fatal_error_message
  - file_header
  #- file_name
  - first_where
  - identical_operands
  #- implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  #- literal_expression_end_indentation
  - lower_acl_than_parent
  #- missing_docs
  - modifier_order
  #- multiline_arguments
  #- multiline_function_chains
  #- multiline_parameters
  #- no_grouping_extension
  - object_literal
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  #- static_operator
  #- strict_fileprivate
  - strong_iboutlet
  - toggle_bool
  #- unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  #- vertical_parameter_alignment_on_call
  #- vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition
cyclomatic_complexity: 15
function_parameter_count: 6
vertical_whitespace:
  max_empty_lines: 2
identifier_name:
  max_length:
    warning: 50
    error: 55
  min_length: 2
custom_rules:
  translate_constraints: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    excluded: ".*UIView.?Layout\\.swift" # regex that defines paths to exclude during linting. optional
    name: "translatesAutoresizingMaskIntoConstraints usage" # rule name. optional.
    regex: "(translatesAutoresizingMaskIntoConstraints.?=.?false)" # matching pattern
    message: "No need to use translatesAutoresizingMaskIntoConstraints anymore, as it is automatically set in UIView+Layout.swift"
    severity: warning

  use_behavior_relay: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    name: "Variable usage" # rule name. optional.
    regex: "Variable[<(]" # matching pattern
    message: "Please use BehaviorRelay instead of Variable, as it will be deprecated soon"
    severity: warning
